
module load python/3.12.1

######### p0.05

sbatch -p general --time=10:00:00 --mem=96g --wrap="hmseekr_seqstosummary -qf './fastaFiles/NEAT1chk1.fa' -td './filterfiles/optimized_transit_NEAT1chk1.csv' -lf './filterfiles/lenfilter_NEAT1chk1.csv' -nf 'v47.lncRNA.can.500.nodup.OT1fixed.fa' -pool 'v47_filtered_ot1fixed_combined.fa' -bkgf 'v47.lncRNA.can.500.nodup.OT1fixed.fa' -k 4 -fc 'findhits_condE' -pf 0.05 -name 'NEAT1chk1' -dir './sts_NEAT1chk1/' -format wide -a 'ATCG' -pb"
sbatch -p general --time=10:00:00 --mem=96g --wrap="hmseekr_seqstosummary -qf './fastaFiles/NEAT1chk910.fa' -td './filterfiles/optimized_transit_NEAT1chk910.csv' -lf './filterfiles/lenfilter_NEAT1chk910.csv' -nf 'v47.lncRNA.can.500.nodup.OT1fixed.fa' -pool 'v47_filtered_ot1fixed_combined.fa' -bkgf 'v47.lncRNA.can.500.nodup.OT1fixed.fa' -k 4 -fc 'findhits_condE' -pf 0.05 -name 'NEAT1chk910' -dir './sts_NEAT1chk910/' -format wide -a 'ATCG' -pb"
sbatch -p general --time=10:00:00 --mem=96g --wrap="hmseekr_seqstosummary -qf './fastaFiles/NEAT1chk1116.fa' -td './filterfiles/optimized_transit_NEAT1chk1116.csv' -lf './filterfiles/lenfilter_NEAT1chk1116.csv' -nf 'v47.lncRNA.can.500.nodup.OT1fixed.fa' -pool 'v47_filtered_ot1fixed_combined.fa' -bkgf 'v47.lncRNA.can.500.nodup.OT1fixed.fa' -k 4 -fc 'findhits_condE' -pf 0.05 -name 'NEAT1chk1116' -dir './sts_NEAT1chk1116/' -format wide -a 'ATCG' -pb"
sbatch -p general --time=10:00:00 --mem=96g --wrap="hmseekr_seqstosummary -qf './fastaFiles/NEAT1chk22.fa' -td './filterfiles/optimized_transit_NEAT1chk22.csv' -lf './filterfiles/lenfilter_NEAT1chk22.csv' -nf 'v47.lncRNA.can.500.nodup.OT1fixed.fa' -pool 'v47_filtered_ot1fixed_combined.fa' -bkgf 'v47.lncRNA.can.500.nodup.OT1fixed.fa' -k 4 -fc 'findhits_condE' -pf 0.05 -name 'NEAT1chk22' -dir './sts_NEAT1chk22/' -format wide -a 'ATCG' -pb"



sbatch -p general --time=10:00:00 --mem=96g --wrap="hmseekr_seqstosummary -qf './fastaFiles/XISTrA.fa' -td './filterfiles/optimized_transit_XISTrA.csv' -lf './filterfiles/lenfilter_XISTrA.csv' -nf 'v47.lncRNA.can.500.nodup.OT1fixed.fa' -pool 'v47_filtered_ot1fixed_combined.fa' -bkgf 'v47.lncRNA.can.500.nodup.OT1fixed.fa' -k 4 -fc 'findhits_condE' -pf 0.05 -name 'XISTrA' -dir './sts_XISTrA/' -format wide -a 'ATCG' -pb"
sbatch -p general --time=10:00:00 --mem=96g --wrap="hmseekr_seqstosummary -qf './fastaFiles/XISTrB12.fa' -td './filterfiles/optimized_transit_XISTrB12.csv' -lf './filterfiles/lenfilter_XISTrB12.csv' -nf 'v47.lncRNA.can.500.nodup.OT1fixed.fa' -pool 'v47_filtered_ot1fixed_combined.fa' -bkgf 'v47.lncRNA.can.500.nodup.OT1fixed.fa' -k 4 -fc 'findhits_condE' -pf 0.05 -name 'XISTrB12' -dir './sts_XISTrB12/' -format wide -a 'ATCG' -pb"
sbatch -p general --time=10:00:00 --mem=96g --wrap="hmseekr_seqstosummary -qf './fastaFiles/XISTrD.fa' -td './filterfiles/optimized_transit_XISTrD.csv' -lf './filterfiles/lenfilter_XISTrD.csv' -nf 'v47.lncRNA.can.500.nodup.OT1fixed.fa' -pool 'v47_filtered_ot1fixed_combined.fa' -bkgf 'v47.lncRNA.can.500.nodup.OT1fixed.fa' -k 4 -fc 'findhits_condE' -pf 0.05 -name 'XISTrD' -dir './sts_XISTrD/' -format wide -a 'ATCG' -pb"
sbatch -p general --time=10:00:00 --mem=96g --wrap="hmseekr_seqstosummary -qf './fastaFiles/XISTrE.fa' -td './filterfiles/optimized_transit_XISTrE.csv' -lf './filterfiles/lenfilter_XISTrE.csv' -nf 'v47.lncRNA.can.500.nodup.OT1fixed.fa' -pool 'v47_filtered_ot1fixed_combined.fa' -bkgf 'v47.lncRNA.can.500.nodup.OT1fixed.fa' -k 4 -fc 'findhits_condE' -pf 0.05 -name 'XISTrE' -dir './sts_XISTrE/' -format wide -a 'ATCG' -pb"
sbatch -p general --time=10:00:00 --mem=96g --wrap="hmseekr_seqstosummary -qf './fastaFiles/XISTrF.fa' -td './filterfiles/optimized_transit_XISTrF.csv' -lf './filterfiles/lenfilter_XISTrF.csv' -nf 'v47.lncRNA.can.500.nodup.OT1fixed.fa' -pool 'v47_filtered_ot1fixed_combined.fa' -bkgf 'v47.lncRNA.can.500.nodup.OT1fixed.fa' -k 4 -fc 'findhits_condE' -pf 0.05 -name 'XISTrF' -dir './sts_XISTrF/' -format wide -a 'ATCG' -pb"



######### p0.01

sbatch -p general --time=10:00:00 --mem=96g --wrap="hmseekr_seqstosummary -qf './fastaFiles/NEAT1chk1.fa' -td './filterfiles/optimized_transit_NEAT1chk1.csv' -lf './filterfiles/lenfilter_NEAT1chk1.csv' -nf 'v47.lncRNA.can.500.nodup.OT1fixed.fa' -pool 'v47_filtered_ot1fixed_combined.fa' -bkgf 'v47.lncRNA.can.500.nodup.OT1fixed.fa' -k 4 -fc 'findhits_condE' -pf 0.01 -name 'NEAT1chk1' -dir './sts_NEAT1chk1/' -format wide -a 'ATCG' -pb"
sbatch -p general --time=10:00:00 --mem=96g --wrap="hmseekr_seqstosummary -qf './fastaFiles/NEAT1chk910.fa' -td './filterfiles/optimized_transit_NEAT1chk910.csv' -lf './filterfiles/lenfilter_NEAT1chk910.csv' -nf 'v47.lncRNA.can.500.nodup.OT1fixed.fa' -pool 'v47_filtered_ot1fixed_combined.fa' -bkgf 'v47.lncRNA.can.500.nodup.OT1fixed.fa' -k 4 -fc 'findhits_condE' -pf 0.01 -name 'NEAT1chk910' -dir './sts_NEAT1chk910/' -format wide -a 'ATCG' -pb"
sbatch -p general --time=10:00:00 --mem=96g --wrap="hmseekr_seqstosummary -qf './fastaFiles/NEAT1chk1116.fa' -td './filterfiles/optimized_transit_NEAT1chk1116.csv' -lf './filterfiles/lenfilter_NEAT1chk1116.csv' -nf 'v47.lncRNA.can.500.nodup.OT1fixed.fa' -pool 'v47_filtered_ot1fixed_combined.fa' -bkgf 'v47.lncRNA.can.500.nodup.OT1fixed.fa' -k 4 -fc 'findhits_condE' -pf 0.01 -name 'NEAT1chk1116' -dir './sts_NEAT1chk1116/' -format wide -a 'ATCG' -pb"
sbatch -p general --time=10:00:00 --mem=96g --wrap="hmseekr_seqstosummary -qf './fastaFiles/NEAT1chk22.fa' -td './filterfiles/optimized_transit_NEAT1chk22.csv' -lf './filterfiles/lenfilter_NEAT1chk22.csv' -nf 'v47.lncRNA.can.500.nodup.OT1fixed.fa' -pool 'v47_filtered_ot1fixed_combined.fa' -bkgf 'v47.lncRNA.can.500.nodup.OT1fixed.fa' -k 4 -fc 'findhits_condE' -pf 0.01 -name 'NEAT1chk22' -dir './sts_NEAT1chk22/' -format wide -a 'ATCG' -pb"



sbatch -p general --time=10:00:00 --mem=96g --wrap="hmseekr_seqstosummary -qf './fastaFiles/XISTrA.fa' -td './filterfiles/optimized_transit_XISTrA.csv' -lf './filterfiles/lenfilter_XISTrA.csv' -nf 'v47.lncRNA.can.500.nodup.OT1fixed.fa' -pool 'v47_filtered_ot1fixed_combined.fa' -bkgf 'v47.lncRNA.can.500.nodup.OT1fixed.fa' -k 4 -fc 'findhits_condE' -pf 0.01 -name 'XISTrA' -dir './sts_XISTrA/' -format wide -a 'ATCG' -pb"
sbatch -p general --time=10:00:00 --mem=96g --wrap="hmseekr_seqstosummary -qf './fastaFiles/XISTrB12.fa' -td './filterfiles/optimized_transit_XISTrB12.csv' -lf './filterfiles/lenfilter_XISTrB12.csv' -nf 'v47.lncRNA.can.500.nodup.OT1fixed.fa' -pool 'v47_filtered_ot1fixed_combined.fa' -bkgf 'v47.lncRNA.can.500.nodup.OT1fixed.fa' -k 4 -fc 'findhits_condE' -pf 0.01 -name 'XISTrB12' -dir './sts_XISTrB12/' -format wide -a 'ATCG' -pb"
sbatch -p general --time=10:00:00 --mem=96g --wrap="hmseekr_seqstosummary -qf './fastaFiles/XISTrD.fa' -td './filterfiles/optimized_transit_XISTrD.csv' -lf './filterfiles/lenfilter_XISTrD.csv' -nf 'v47.lncRNA.can.500.nodup.OT1fixed.fa' -pool 'v47_filtered_ot1fixed_combined.fa' -bkgf 'v47.lncRNA.can.500.nodup.OT1fixed.fa' -k 4 -fc 'findhits_condE' -pf 0.01 -name 'XISTrD' -dir './sts_XISTrD/' -format wide -a 'ATCG' -pb"
sbatch -p general --time=10:00:00 --mem=96g --wrap="hmseekr_seqstosummary -qf './fastaFiles/XISTrE.fa' -td './filterfiles/optimized_transit_XISTrE.csv' -lf './filterfiles/lenfilter_XISTrE.csv' -nf 'v47.lncRNA.can.500.nodup.OT1fixed.fa' -pool 'v47_filtered_ot1fixed_combined.fa' -bkgf 'v47.lncRNA.can.500.nodup.OT1fixed.fa' -k 4 -fc 'findhits_condE' -pf 0.01 -name 'XISTrE' -dir './sts_XISTrE/' -format wide -a 'ATCG' -pb"
sbatch -p general --time=10:00:00 --mem=96g --wrap="hmseekr_seqstosummary -qf './fastaFiles/XISTrF.fa' -td './filterfiles/optimized_transit_XISTrF.csv' -lf './filterfiles/lenfilter_XISTrF.csv' -nf 'v47.lncRNA.can.500.nodup.OT1fixed.fa' -pool 'v47_filtered_ot1fixed_combined.fa' -bkgf 'v47.lncRNA.can.500.nodup.OT1fixed.fa' -k 4 -fc 'findhits_condE' -pf 0.01 -name 'XISTrF' -dir './sts_XISTrF/' -format wide -a 'ATCG' -pb"


######### p0.001

sbatch -p general --time=10:00:00 --mem=96g --wrap="hmseekr_seqstosummary -qf './fastaFiles/NEAT1chk1.fa' -td './filterfiles/optimized_transit_NEAT1chk1.csv' -lf './filterfiles/lenfilter_NEAT1chk1.csv' -nf 'v47.lncRNA.can.500.nodup.OT1fixed.fa' -pool 'v47_filtered_ot1fixed_combined.fa' -bkgf 'v47.lncRNA.can.500.nodup.OT1fixed.fa' -k 4 -fc 'findhits_condE' -pf 0.001 -name 'NEAT1chk1' -dir './sts_NEAT1chk1/' -format wide -a 'ATCG' -pb"
sbatch -p general --time=10:00:00 --mem=96g --wrap="hmseekr_seqstosummary -qf './fastaFiles/NEAT1chk910.fa' -td './filterfiles/optimized_transit_NEAT1chk910.csv' -lf './filterfiles/lenfilter_NEAT1chk910.csv' -nf 'v47.lncRNA.can.500.nodup.OT1fixed.fa' -pool 'v47_filtered_ot1fixed_combined.fa' -bkgf 'v47.lncRNA.can.500.nodup.OT1fixed.fa' -k 4 -fc 'findhits_condE' -pf 0.001 -name 'NEAT1chk910' -dir './sts_NEAT1chk910/' -format wide -a 'ATCG' -pb"
sbatch -p general --time=10:00:00 --mem=96g --wrap="hmseekr_seqstosummary -qf './fastaFiles/NEAT1chk1116.fa' -td './filterfiles/optimized_transit_NEAT1chk1116.csv' -lf './filterfiles/lenfilter_NEAT1chk1116.csv' -nf 'v47.lncRNA.can.500.nodup.OT1fixed.fa' -pool 'v47_filtered_ot1fixed_combined.fa' -bkgf 'v47.lncRNA.can.500.nodup.OT1fixed.fa' -k 4 -fc 'findhits_condE' -pf 0.001 -name 'NEAT1chk1116' -dir './sts_NEAT1chk1116/' -format wide -a 'ATCG' -pb"
sbatch -p general --time=10:00:00 --mem=96g --wrap="hmseekr_seqstosummary -qf './fastaFiles/NEAT1chk22.fa' -td './filterfiles/optimized_transit_NEAT1chk22.csv' -lf './filterfiles/lenfilter_NEAT1chk22.csv' -nf 'v47.lncRNA.can.500.nodup.OT1fixed.fa' -pool 'v47_filtered_ot1fixed_combined.fa' -bkgf 'v47.lncRNA.can.500.nodup.OT1fixed.fa' -k 4 -fc 'findhits_condE' -pf 0.001 -name 'NEAT1chk22' -dir './sts_NEAT1chk22/' -format wide -a 'ATCG' -pb"



sbatch -p general --time=10:00:00 --mem=96g --wrap="hmseekr_seqstosummary -qf './fastaFiles/XISTrA.fa' -td './filterfiles/optimized_transit_XISTrA.csv' -lf './filterfiles/lenfilter_XISTrA.csv' -nf 'v47.lncRNA.can.500.nodup.OT1fixed.fa' -pool 'v47_filtered_ot1fixed_combined.fa' -bkgf 'v47.lncRNA.can.500.nodup.OT1fixed.fa' -k 4 -fc 'findhits_condE' -pf 0.001 -name 'XISTrA' -dir './sts_XISTrA/' -format wide -a 'ATCG' -pb"
sbatch -p general --time=10:00:00 --mem=96g --wrap="hmseekr_seqstosummary -qf './fastaFiles/XISTrB12.fa' -td './filterfiles/optimized_transit_XISTrB12.csv' -lf './filterfiles/lenfilter_XISTrB12.csv' -nf 'v47.lncRNA.can.500.nodup.OT1fixed.fa' -pool 'v47_filtered_ot1fixed_combined.fa' -bkgf 'v47.lncRNA.can.500.nodup.OT1fixed.fa' -k 4 -fc 'findhits_condE' -pf 0.001 -name 'XISTrB12' -dir './sts_XISTrB12/' -format wide -a 'ATCG' -pb"
sbatch -p general --time=10:00:00 --mem=96g --wrap="hmseekr_seqstosummary -qf './fastaFiles/XISTrD.fa' -td './filterfiles/optimized_transit_XISTrD.csv' -lf './filterfiles/lenfilter_XISTrD.csv' -nf 'v47.lncRNA.can.500.nodup.OT1fixed.fa' -pool 'v47_filtered_ot1fixed_combined.fa' -bkgf 'v47.lncRNA.can.500.nodup.OT1fixed.fa' -k 4 -fc 'findhits_condE' -pf 0.001 -name 'XISTrD' -dir './sts_XISTrD/' -format wide -a 'ATCG' -pb"
sbatch -p general --time=10:00:00 --mem=96g --wrap="hmseekr_seqstosummary -qf './fastaFiles/XISTrE.fa' -td './filterfiles/optimized_transit_XISTrE.csv' -lf './filterfiles/lenfilter_XISTrE.csv' -nf 'v47.lncRNA.can.500.nodup.OT1fixed.fa' -pool 'v47_filtered_ot1fixed_combined.fa' -bkgf 'v47.lncRNA.can.500.nodup.OT1fixed.fa' -k 4 -fc 'findhits_condE' -pf 0.001 -name 'XISTrE' -dir './sts_XISTrE/' -format wide -a 'ATCG' -pb"
sbatch -p general --time=10:00:00 --mem=96g --wrap="hmseekr_seqstosummary -qf './fastaFiles/XISTrF.fa' -td './filterfiles/optimized_transit_XISTrF.csv' -lf './filterfiles/lenfilter_XISTrF.csv' -nf 'v47.lncRNA.can.500.nodup.OT1fixed.fa' -pool 'v47_filtered_ot1fixed_combined.fa' -bkgf 'v47.lncRNA.can.500.nodup.OT1fixed.fa' -k 4 -fc 'findhits_condE' -pf 0.001 -name 'XISTrF' -dir './sts_XISTrF/' -format wide -a 'ATCG' -pb"


