# randomly insert query to a transcript in pool and findhits to test recovery

import pandas as pd
import numpy as np
import random
import os
from Bio import SeqIO
from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord
import tempfile
import shutil
import matplotlib.pyplot as plt

from seekr.kmer_counts import BasicCounter as seekrBasicCounter 
from seekr.pearson import pearson as seekrPearson
from seekr.find_pval import find_pval
from seekr.find_dist import find_dist

from hmseekr.findhits_condE import findhits_condE

# Read all sequences into a list
# queries = list(SeqIO.parse('XKNM_chunks.fa', "fasta")) #112
pool=list(SeqIO.parse('../../v47_filtered_ot1fixed_combined.fa', "fasta")) # 6663

def overlap_percentage(real_start: int,
                       real_len:   int,
                       guesses:    pd.DataFrame) -> float:
    """
    Compute what fraction of [real_start, real_end] is covered by
    a set of non-overlapping guess intervals in `guesses`.

    Parameters
    ----------
    real_start : int
        Start position (inclusive) of the true insertion.
    real_end : int
        End position (inclusive) of the true insertion.
    guesses : pd.DataFrame
        Must have integer columns 'start' and 'end', non-overlapping.

    Returns
    -------
    float
        Percent overlap: (covered bp / real bp) * 100.
    """
    real_end = real_start + real_len - 1
    # if real_len <= 0:
    #     raise ValueError("real_end must be ≥ real_start")

    covered = 0
    for _, row in guesses.iterrows():
        gs, ge = row['Start'], row['End']
        # find intersection of [real_start, real_end] & [gs, ge]
        ov_start = max(real_start, gs)
        ov_end   = min(real_end,   ge)
        if ov_end >= ov_start:
            covered += (ov_end - ov_start + 1)

    # guard against >100% if guesses somehow overlap or extend
    # covered = min(covered, real_len)
    return (covered / real_len) * 100

# read in lengthfilter
lenfilter=pd.read_csv('lengthfilter_XNM.csv', sep=',')

# load in the background sequences and calculate the seekr norm vectors
print('Calculating background norm vectors')
print('This could take a while if the background fasta file is large')
bkg_norm = seekrBasicCounter('../../v47.lncRNA.can.500.nodup.OT1fixed.fa', k=4, log2='Log2.post', silent=True) 
bkg_norm.get_counts() 

mean_path = f'./bkg_mean_norm_4mers.npy' 
std_path = f'./bkg_std_norm_4mers.npy' 
np.save(mean_path, bkg_norm.mean)
np.save(std_path, bkg_norm.std)
print('Background norm vectors saved')

# find the dist of background
fitres = find_dist(inputseq='../../v47.lncRNA.can.500.nodup.OT1fixed.fa', k_mer=4, models='common10', 
                    subsetting=True, subset_size = 10000, 
                    fit_model=True, statsmethod='ks',progress_bar=False, 
                    plotfit='modelfitplot', outputname='fitres')
plt.close('all')
# delete the intermediate files generated by find_dist
os.remove(f'bkg_mean_4mers.npy')
os.remove(f'bkg_std_4mers.npy')

# Module-level LUTs (build once)
_LUT_TO = np.full(256, -1, dtype=np.int8)
for b, i in [(ord('A'),0), (ord('T'),1), (ord('G'),2), (ord('C'),3)]:
    _LUT_TO[b] = i
_INV = np.frombuffer(b"ATGC", dtype=np.uint8)

def mutate_dna_numpy(seq: str, frac: float = 0.40) -> str:
    
    rng = np.random.default_rng()
    s = np.frombuffer(seq.encode("ascii"), dtype=np.uint8).copy()
    n = s.size
    k = max(1, int(round(n * frac)))
    idxs = rng.choice(n, size=k, replace=False)

    cur = _LUT_TO[s[idxs]]            # 0..3
    r = rng.integers(0, 3, size=k)    # 0,1,2
    new_idx = (cur + 1 + r) & 3       # one of the other 3 bases
    s[idxs] = _INV[new_idx]

    return s.tobytes().decode("ascii")




for record in SeqIO.parse('XNM_chunks.fa', 'fasta'):
    name = record.id           
    seq  = str(record.seq)

    # save this seq into a fasta file
    with open('query.fa', 'w') as f:
        SeqIO.write(record, f, 'fasta')
    

    if name in lenfilter["query"].values:
        lmin = lenfilter.loc[lenfilter["query"] == name, "lenmin"].iloc[0]
        lmax = lenfilter.loc[lenfilter["query"] == name, "lenmax"].iloc[0]
    else:
        lmin = 200
        lmax = 6000
    
    print(name,flush=True)
    
    # assemble model dir
    modeldir=f'../../seqstosummary/markovModels/{name}_v47TSC/4/hmm.dict'
    

    results = []
    # repeat 1000 times
    for rep in range(1000):
        
        if rep % 100 == 0:
            print(f"At rep {rep}",flush=True)

    
        # random select a seq in pool
        pool_rec = random.choice(pool)
        pool_seq = str(pool_rec.seq)

        # choose an insertion point
        insert_pos = random.randint(0, len(pool_seq))

        # mutate 
        mutated_query = mutate_dna_numpy(seq, frac=0.40)

        # insert the query into the seq
        new_seq = pool_seq[:insert_pos] + mutated_query + pool_seq[insert_pos:]

        new_rec = SeqRecord(Seq(new_seq),id=pool_rec.id)

        # write it out to a uniquely named temp file
        with tempfile.NamedTemporaryFile(mode='w+', suffix='.fa', delete=False) as tmp:
            SeqIO.write(
                SeqRecord(Seq(new_seq),
                          id=record.id),
                tmp, 'fasta'
            )
            tmp_path = tmp.name

        testhits = findhits_condE(searchpool=tmp_path,
                                  modeldir=modeldir,
                                  knum=4,outputname='hits',outputdir='./intermediates_hits/',
                                  alphabet='ATCG',fasta=True,progressbar=False)

        # only keep the rows in hits if Length col is greater than lengthfilter
        testhits = testhits[testhits['Length']>lmin]
        testhits = testhits[testhits['Length']<lmax]

        # check if there are any hits left after filtering
        # if not, return an empty dataframe and print warning
        if testhits.shape[0] == 0:
            print('No hits left after length filtering')
            print('Please adjust the length filter lenmin and lenmax')
            print('No file is saved')
            # stash your metrics
            results.append({
                'query_id':   name,
                'pool_id':    pool_rec.id,
                'insert_pos': insert_pos,
                'recover_pert':   0.0,
                'recover_pert_0.05':   0.0,
                'recover_pert_0.01':   0.0,
                'recover_pert_0.001':  0.0
            })
            
            os.remove(tmp_path)
            if os.path.exists('./hits_4_viterbi.txt'):
                os.remove('./hits_4_viterbi.txt')
            # move on to the next rep
            continue

        # save the hits sequences
        hits_seq = testhits['Sequence']
        hits_header = testhits['seqName']+'_'+testhits['Start'].astype(str)+'_'+testhits['End'].astype(str)
        hitseqdir = './intermediates_hits/hits_seqs.fa'
        
        # save the hits sequences and its header to a fasta file
        with open(hitseqdir, 'w') as f:
            for i in range(len(hits_seq)):
                f.write(f'{hits_header.iloc[i]}\n{hits_seq.iloc[i]}\n')

        # calculate r value
        query_count = seekrBasicCounter(infasta='query.fa', outfile='intermediates_hits/seekrquery_counts.csv', k=4, mean=mean_path, std=std_path, log2='Log2.post', silent=True) 
        query_count.make_count_file()

        hits_count = seekrBasicCounter(infasta=hitseqdir, outfile='intermediates_hits/seekrhits_counts.csv', k=4, mean=mean_path, std=std_path, log2='Log2.post', silent=True) 
        hits_count. make_count_file()

        sim = seekrPearson(hits_count.counts,query_count.counts)
        testhits['seekr_rval']=sim

        # find the p value of the seekr r score
        pvals=find_pval(seq1file=hitseqdir, seq2file='query.fa', 
                        mean_path=mean_path, std_path=std_path,
                        k_mer=4, fitres=fitres, log2='Log2.post', 
                        bestfit=1, outputname=f'intermediates_hits/hits_seekr_pval', progress_bar=False)
        
        # change the first column name of pvals
        pvals.columns = ['seekr_pval']
        pvals = pvals.reset_index(drop=True)
        testhits = testhits.reset_index(drop=True)

        # add the pvals seekr_pval values to the hits dataframe as a new column seekr_pval
        testhits['seekr_pval'] = pvals['seekr_pval']

        cov_pert = overlap_percentage(insert_pos, len(seq), testhits)
        # filter by seekr_pval <0.05
        testhits005 = testhits[testhits['seekr_pval']<0.05]
        cov_pert005 = overlap_percentage(insert_pos, len(seq), testhits005)
        # filter by seekr_pval <0.01
        testhits001 = testhits[testhits['seekr_pval']<0.01]
        cov_pert001 = overlap_percentage(insert_pos, len(seq), testhits001)
        # filter by seekr_pval <0.001
        testhits0001 = testhits[testhits['seekr_pval']<0.001]
        cov_pert0001 = overlap_percentage(insert_pos, len(seq), testhits0001)


        # clean up the temp file
        os.remove(tmp_path)
        if os.path.exists('./hits_4_viterbi.txt'):
            os.remove('./hits_4_viterbi.txt')


        if os.path.exists('./intermediates_hits'):
            shutil.rmtree('./intermediates_hits')

        # stash your metrics
        results.append({
            'query_id':   name,
            'pool_id':    pool_rec.id,
            'insert_pos': insert_pos,
            'recover_pert':   cov_pert,
            'recover_pert_0.05':   cov_pert005,
            'recover_pert_0.01':   cov_pert001,
            'recover_pert_0.001':  cov_pert0001
        })
        
    # 4) once everything’s done, dump to CSV
    if os.path.exists('./query.fa'):
        os.remove('./query.fa')
        
    df = pd.DataFrame(results)
    df.to_csv(f'{name}_recover_percentage.csv', index=False)
    
